[tool.black]
target-version = ['py310']

[tool.isort]
profile = "black"
known_third_party = ["alembic", "flask", "flask_bootstrap", "flask_migrate", "flask_sqlalchemy", "sqlalchemy", "sqlalchemy_utils", "werkzeug"]

[tool.pylint.format]
max-line-length = 88
