[tool.black]
target-version = ['py311']

[tool.isort]
profile = "black"
known_third_party = ["alembic", "factory", "faker", "flask", "flask_bootstrap", "flask_login", "flask_migrate", "flask_sqlalchemy", "flask_wtf", "markupsafe", "pytest", "sqlalchemy", "sqlalchemy_utils", "werkzeug", "wtforms"]

[tool.pylint.format]
max-line-length = 88
ignored-classes=["scoped_session"]

[tool.pytest.ini_options]
python_files = ["tests.py", "test_*.py"]
filterwarnings = ["ignore::DeprecationWarning"]
