"""Connect representative student

Revision ID: 36e2e5e23bce
Revises: 1823b06c8d8d
Create Date: 2022-10-13 22:08:42.004404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e2e5e23bce'
down_revision = '1823b06c8d8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('representative_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student', 'representative', ['representative_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_column('student', 'representative_id')
    # ### end Alembic commands ###
