"""Class model

Revision ID: 5a2068ec2caf
Revises: ac879c7faf9a
Create Date: 2022-10-14 16:39:13.735760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a2068ec2caf'
down_revision = 'ac879c7faf9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('NORMAL', 'INTENSIVE', name='mode'), nullable=False),
    sa.Column('start_at', sa.Time(), nullable=False),
    sa.Column('end_at', sa.Time(), nullable=False),
    sa.Column('level', sa.Enum('L1', 'L2', 'L3', name='level'), nullable=False),
    sa.Column('sub_level', sa.Enum('P1', 'P2', 'P3', 'P4', name='sub_level'), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle.id'], name=op.f('fk_class_cycle_id_cycle')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class'))
    )
    op.add_column('student', sa.Column('class_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_student_class_id_class'), 'student', 'class', ['class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_student_class_id_class'), 'student', type_='foreignkey')
    op.drop_column('student', 'class_id')
    op.drop_table('class')
    # ### end Alembic commands ###
