"""Payment model

Revision ID: d106bc80fa1b
Revises: 5a2068ec2caf
Create Date: 2022-10-15 07:07:17.442666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd106bc80fa1b'
down_revision = '5a2068ec2caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.Unicode(length=255), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle.id'], name=op.f('fk_payment_cycle_id_cycle')),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_payment_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    # ### end Alembic commands ###
